### ISSUE TITLE
Changes to mongo auth

### ISSUE THREAD

**Issue by tkeemon** [appsembler/configuration#36]
By default, mongo auth is turned off, which means that read/write permissions aren't enforced:
https://github.com/edx/configuration/blob/master/playbooks/roles/mongo_2_6/templates/mongodb.conf.j2#L37-L39

If we're enabling auth on Mongo, then our backup script needs a username/password with proper access: 
https://github.com/appsembler/configuration/blob/appsembler/master/playbooks/roles/backups/files/backup.py

This is a working `mongodump` command for reference: 
```
mongodump -u admin --authenticationDatabase admin -p ADMIN_PASSWORD -o /path/for/dump.mongo
```

**Comment by mrgnr** [comment]
Fixed by https://github.com/appsembler/configuration/pull/38
